title: RoboWled
description: A WPILib-compatible library for controlling WLED LED strips on FRC robots
baseurl: "/RoboWled"
url: "https://team9567.github.io"

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

markdown: kramdown

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - SUMMARY.md
